### PR TITLE
Add support for jmeter-plugin graph output file

### PR DESCRIPTION
**Pull request by jaredculp**
If this looks good, I'll add it to the rest of the plugins, and maybe try to pull more common functionality into `base_plugin.rb`

### CODE REVIEW

**Comment by jaredculp** [comment]
ping @90kts

**Comment by 90kts** [comment]
Hi thanks for starting this. 

At the moment there's no need for an additional base class to be extended, the filename parameter should work via the [update method](https://github.com/flood-io/ruby-jmeter/blob/master/lib/ruby-jmeter/helpers/helper.rb#L18) e.g.:

```
response_times_percentiles 'Response Times Percentiles', filename: '/path/to/your/file.xml'
```

The boolean can also be set via update_at_xpath helper which will need to be patched into the plugin definitions [like this](https://github.com/flood-io/ruby-jmeter/commit/a0e912d842562d0e84671bd89601a439fa58e654#diff-93800691e441cb5b8b6b23ae149a9872R45).

Full example here: https://github.com/flood-io/ruby-jmeter/blob/master/examples/basic_response_time_percentiles_graph.rb

**Comment by jaredculp** [comment]
I'm having a hard time getting graphs to output as `png` files when I run in headless mode, which I thought I could solve with this change, but this seems like it just outputs XML which I'm still going to need to feed into something else.

Am I missing something here?

**Comment by 90kts** [comment]
I think you want to use the graph generator instead and output PNGs. Not sure if we have that plumbed in to ruby-jmeter but you're welcome to add it.

http://www.ubik-ingenierie.com/blog/automatically-generating-nice-graphs-at-end-of-your-load-test-with-apache-jmeter-and-jmeter-plugins/

**Comment by jaredculp** [comment]
I'm going to close this. Thanks!

**Pull request closed without merging**
