### PR TITLE
Add redis data set config from jmeter-plugins extras with libs

### PR DESCRIPTION
**Pull request by sworisbreathing**
This PR adds DSL support for the [Redis Data Set](http://jmeter-plugins.org/wiki/RedisDataSet/) from jmeter plugins' extras with libs set.

It also shows a working example of the redis data set, including a setup thread group with a groovy script for preseeding the redis data.

### CODE REVIEW

**Comment by sworisbreathing** [comment]
@90kts have you had a chance to take a look at this one yet? I'm running a locally-built gem with the PR added but pretty keen to get back onto an official release.

**Comment by sworisbreathing** [comment]
cheers

**Comment by 90kts** [comment]
ruby-jmeter 2.13.9 built to pkg/ruby-jmeter-2.13.9.gem.
Tagged v2.13.9.

**Comment by 90kts** [comment]
thanks

**Pull request merged**
