### PR TITLE
Fix jsr223 assertion

### PR DESCRIPTION
**Pull request by cyberw**

### CODE REVIEW

**Comment by 90kts** [comment]
Thank you for the PR, please use the update_at_xpath parameter instead as per this example: https://github.com/flood-io/ruby-jmeter/blob/master/examples/jsr223_assertion.rb

Main reason is we are not in control of ordering of DSL elements as extracted from JMeter via the IDL (process)

**Comment by cyberw** [comment]
But we shouldn't have duplicate entries for jsr223_assertion in the xml, right? Seems something goes wrong during the IDL...

**Comment by 90kts** [comment]
It's not so much a case of duplicate entries in the source XML (which is valid XML according to JMeter 3.0) https://github.com/flood-io/ruby-jmeter/blob/master/lib/ruby-jmeter/idl.xml#L918-L923

It's more the case the update method https://github.com/flood-io/ruby-jmeter/blob/master/lib/ruby-jmeter/helpers/helper.rb#L24 does a string search for name contains - this is so we don't need to specify the full name for attributes in the DSL.

However in this case if we specify `script` and `scriptLanguage` attributes in the DSL, the search returns the same (first) attribute which is not desired behaviour. Which is also why using `update_at_xpath` for a specific attribute is more accurate / works.

Hope that makes sense!

**Comment by cyberw** [comment]
I understand that it is valid XML to have duplicate entries, but not WHY we should have duplicate entries :)

I also get why update_at_xpath works. Would it make sense to change the update method so that it prefers exact matches if one exists?

**Comment by 90kts** [comment]
Where are the duplicate entries? Maybe I missed that?

The fuzzy update is useful so that you don't need to full name. We could
probably guess the prefix but it's nice to be able to just specify domain:
without specifying 'HTTPSampler.domain':

**Comment by 90kts** [comment]
Never mind, I see what you mean:
https://s3.amazonaws.com/flood-io-support/idl.xml_UserstimkoopmansGitfloodruby-jmeterlibruby-jmeteridl.xml_-_Apache_JMeter_3.0_r1743807_2016-08-09_18-50-57.png

**Comment by cyberw** [comment]
Exactly. And what I mean is not that we should take away fuzzy matching, just that we should prefer an exact match *if one exists*.

**Comment by 90kts** [comment]
OK cool. I've just patched the dupes with ruby-jmeter-3.0.1.

Would welcome a PR if you can figure out a better exact match (with
fallback to fuzzy) logic here:
https://github.com/flood-io/ruby-jmeter/blob/master/lib/ruby-jmeter/helpers/helper.rb#L24

Thanks for your input!

Regards,
​Tim

**Pull request closed without merging**
